# Generated by Django 5.1.4 on 2025-08-07 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Righttablelist',
            fields=[
                ('name', models.TextField(blank=True, db_column='Name')),
                ('description', models.TextField(blank=True, db_column='Description', null=True)),
                ('tname', models.TextField(blank=True, db_column='Tname', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'RightTableList',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ChildLabour',
            fields=[
                ('section', models.AutoField(primary_key=True, serialize=False)),
                ('chapter', models.IntegerField()),
                ('name', models.TextField()),
                ('name_ta', models.TextField(blank=True, null=True)),
                ('title', models.TextField()),
                ('title_ta', models.TextField(blank=True, null=True)),
                ('description', models.TextField()),
                ('summary', models.TextField()),
                ('summary_ta', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ChildLabour',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Disabilities',
            fields=[
                ('section', models.AutoField(primary_key=True, serialize=False)),
                ('chapter', models.IntegerField()),
                ('name', models.TextField()),
                ('name_ta', models.TextField(blank=True, null=True)),
                ('title', models.TextField()),
                ('title_ta', models.TextField(blank=True, null=True)),
                ('description', models.TextField()),
                ('summary', models.TextField()),
                ('summary_ta', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Disabilities',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('section', models.AutoField(primary_key=True, serialize=False)),
                ('chapter', models.IntegerField()),
                ('name', models.TextField()),
                ('name_ta', models.TextField(blank=True, null=True)),
                ('title', models.TextField()),
                ('title_ta', models.TextField(blank=True, null=True)),
                ('description', models.TextField()),
                ('summary', models.TextField()),
                ('summary_ta', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Education',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='FoodSecurity',
            fields=[
                ('section', models.AutoField(primary_key=True, serialize=False)),
                ('chapter', models.IntegerField()),
                ('name', models.TextField()),
                ('name_ta', models.TextField(blank=True, null=True)),
                ('title', models.TextField()),
                ('title_ta', models.TextField(blank=True, null=True)),
                ('description', models.TextField()),
                ('summary', models.TextField()),
                ('summary_ta', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'FoodSecurity',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='HumanRights',
            fields=[
                ('section', models.AutoField(primary_key=True, serialize=False)),
                ('chapter', models.IntegerField()),
                ('name', models.TextField()),
                ('name_ta', models.TextField(blank=True, null=True)),
                ('title', models.TextField()),
                ('title_ta', models.TextField(blank=True, null=True)),
                ('description', models.TextField()),
                ('summary', models.TextField()),
                ('summary_ta', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'HumanRights',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Information',
            fields=[
                ('section', models.AutoField(primary_key=True, serialize=False)),
                ('chapter', models.IntegerField()),
                ('name', models.TextField()),
                ('name_ta', models.TextField(blank=True, null=True)),
                ('title', models.TextField()),
                ('title_ta', models.TextField(blank=True, null=True)),
                ('description', models.TextField()),
                ('summary', models.TextField()),
                ('summary_ta', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Information',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='LegalServices',
            fields=[
                ('section', models.AutoField(primary_key=True, serialize=False)),
                ('chapter', models.IntegerField()),
                ('name', models.TextField()),
                ('name_ta', models.TextField(blank=True, null=True)),
                ('title', models.TextField()),
                ('title_ta', models.TextField(blank=True, null=True)),
                ('description', models.TextField()),
                ('summary', models.TextField()),
                ('summary_ta', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'LegalServices',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='SCST',
            fields=[
                ('section', models.AutoField(primary_key=True, serialize=False)),
                ('chapter', models.IntegerField()),
                ('name', models.TextField()),
                ('name_ta', models.TextField(blank=True, null=True)),
                ('title', models.TextField()),
                ('title_ta', models.TextField(blank=True, null=True)),
                ('description', models.TextField()),
                ('summary', models.TextField()),
                ('summary_ta', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'SCST',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Surrogacy',
            fields=[
                ('section', models.AutoField(primary_key=True, serialize=False)),
                ('chapter', models.IntegerField()),
                ('name', models.TextField()),
                ('name_ta', models.TextField(blank=True, null=True)),
                ('title', models.TextField()),
                ('title_ta', models.TextField(blank=True, null=True)),
                ('description', models.TextField()),
                ('summary', models.TextField()),
                ('summary_ta', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Surrogacy',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Welfare',
            fields=[
                ('section', models.AutoField(primary_key=True, serialize=False)),
                ('chapter', models.IntegerField()),
                ('name', models.TextField()),
                ('name_ta', models.TextField(blank=True, null=True)),
                ('title', models.TextField()),
                ('title_ta', models.TextField(blank=True, null=True)),
                ('description', models.TextField()),
                ('summary', models.TextField()),
                ('summary_ta', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Welfare',
                'managed': True,
            },
        ),
    ]
